<?php
/**
 * @file
 * Code for the Events feature.
 */

include_once('campuscms_feature_events.features.inc');

/**
 * Implements hook_modules_installed().
 */
function campuscms_feature_events_modules_installed($modules) {
  if (in_array('custom_breadcrumbs', $modules)) {
    _campuscms_feature_events_custom_breadcrumbs();
  }

  if (in_array('custom_breadcrumbs_views', $modules)) {
    _campuscms_feature_events_custom_breadcrumbs_views();
  }
}

// Create some breadcrumbs for the node
function _campuscms_feature_events_custom_breadcrumbs() {
  // Add node breadcrumb.
  $breadcrumb = new stdClass();
  $breadcrumb->name = 'campuscms_feature_events-node-event';
  $breadcrumb->titles = array('Events', '[node:title]');
  $breadcrumb->paths = array('events', '<none>');
  $breadcrumb->visibility_php = '';
  $breadcrumb->node_type = 'event';

  _custom_breadcrumbs_save_breadcrumb('custom_breadcrumbs', 'node', $breadcrumb);
}

// Create some breacrumbs for the /events
function _campuscms_feature_events_custom_breadcrumbs_views() {
  // Add the breadcrumb for the events page
  $breadcrumb = new stdClass();
  $breadcrumb->name = 'campuscms_feature_events-views-events';
  $breadcrumb->titles = array('News');
  $breadcrumb->paths = array('<none>');
  $breadcrumb->visibility_php = '';
  $breadcrumb->views_path = 'events';

  _custom_breadcrumbs_save_breadcrumb('custom_breadcrumbs_views', 'views', $breadcrumb);
}
