<?php
/**
 * Implements hook_install().
 */
function campuscms_feature_events_install() {
  if (module_exists('custom_breadcrumbs')) {
    _campuscms_feature_events_custom_breadcrumbs();

    if (module_exists('custom_breadcrumbs_views')) {
      _campuscms_feature_events_custom_breadcrumbs_views();
    }
  }
}

/**
 * Implements hook_uninstall().
 */
function campuscms_feature_events_uninstall() {
  db_delete('custom_breadcrumb')->condition('name', 'campuscms_feature_events-%', 'LIKE')->execute();
}
